// User action type
export const SIGNING_REQUEST = 'SIGNING_REQUEST';
export const SIGNING_SUCCESS = 'SIGNING_SUCCESS';
export const SIGNING_FAILURE = 'SIGNING_FAILURE';
export const CLEAR_SIGNING_ERRORS = 'CLEAR_SIGNING_ERRORS';
export const SIGNING_OUT = 'SIGNING_OUT';

// Posts actions types
export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE';
export const CLEAR_POSTS_ERRORS = 'CLEAR_POSTS_ERRORS';

export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const CLEAR_GET_POST_DETAILS = 'CLEAR_GET_POST_DETAILS';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const CLEAR_DELETE_POST_SUCCESS = 'CLEAR_DELETE_POST_SUCCESS';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const CLEAR_CREATE_POST_SUCCESS = 'CLEAR_CREATE_POST_SUCCESS';

export const SELECT_IMAGE_FROM_DEVICE_REQUEST =
  'SELECT_IMAGE_FROM_DEVICE_REQUEST';

export const SELECT_IMAGE_FROM_DEVICE_SUCCESS =
  'SELECT_IMAGE_FROM_DEVICE_SUCCESS';

export const SELECT_IMAGE_FROM_DEVICE_FAILURE =
  'SELECT_IMAGE_FROM_DEVICE_FAILURE';

export const CLEAR_SELECT_IMAGE_FROM_DEVICE_SUCCESS =
  'CLEAR_SELECT_IMAGE_FROM_DEVICE_SUCCESS';

export const IS_EDITING_POST = 'IS_EDITING_POST';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';
export const CLEAR_UPDATE_POST_SUCCESS = 'CLEAR_UPDATE_POST_SUCCESS';
